version: "3.8"

services:
  pki:
    image: nginx:stable-alpine
    container_name: pki.local
    restart: always
    volumes:
      - ./http:/usr/share/nginx/html:ro
    networks:
      pki-net:
        aliases:
          - pki.local
    ports:
      - "8080:80"

  web:
    build: ./webserver
    container_name: web.local
    restart: always
    depends_on:
      - pki
    networks:
      pki-net:
        aliases:
          - web.local
    ports:
      - "8443:443"

  client:
    build: ./client
    container_name: client
    depends_on:
      - web
      - pki
    networks:
      pki-net:
    stdin_open: true
    tty: true

networks:
  pki-net:
    driver: bridge
